# Generated by Django 5.1.6 on 2025-02-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_facelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='face_landmarks',
        ),
    ]
