# Generated by Django 5.1.6 on 2025-02-12 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_face_encoding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='emotion',
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.JSONField(blank=True, null=True, verbose_name="Yuz kodlash ma'lumotlari")),
                ('face_landmarks', models.JSONField(blank=True, null=True, verbose_name='Yuz landmarks')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hissiy holat')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aniqlangan vaqt')),
                ('face_landmarks', models.JSONField(blank=True, null=True, verbose_name='Aniqlangan yuz landmarks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.DeleteModel(
            name='FaceLog',
        ),
    ]
