# Generated by Django 5.1.6 on 2025-02-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_emotion_faceencoding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/', verbose_name='Foydalanuvchi rasmi'),
        ),
    ]
