# Generated by Django 5.1.6 on 2025-02-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecognitionlog',
            name='emotion',
            field=models.JSONField(blank=True, null=True, verbose_name='Hissiy holat'),
        ),
    ]
