# Generated by Django 5.2 on 2025-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kamera nomi')),
                ('type', models.CharField(choices=[('usb', 'USB Kamera'), ('ip', 'IP Kamera'), ('ptz', 'PTZ Kamera')], max_length=10, verbose_name='Kamera turi')),
                ('source', models.CharField(max_length=255, verbose_name='Manba (index yoki URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
