# Generated by Django 5.2 on 2025-04-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognitionlog',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera'),
        ),
        migrations.AddField(
            model_name='facerecognitionlog',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='recognized/'),
        ),
    ]
