# Generated by Django 5.2 on 2025-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attendance_options_alter_camera_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facesnapshot',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
