# Generated by Django 5.2 on 2025-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_facesnapshot_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='selected',
            field=models.BooleanField(default=False, verbose_name="Joriy ro'yxatga olayotgan kamera"),
        ),
    ]
