# Generated by Django 5.2 on 2025-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_camera_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='hardware_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
