# Generated by Django 5.1.6 on 2025-02-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceLog',
        ),
    ]
